[package]
name = "sg2"
authors = [
    "Shane Vitarana <s@noreply.publicawesome.com>",
    "John Y <j@noreply.publicawesome.com>",
]
description = "Definition and types for the SG2 interface"
version      = "3.5.0"
edition      = "2021"
homepage     = "https://stargaze.zone"
repository   = "https://github.com/public-awesome/launchpad"
license      = "Apache-2.0"

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
cw-storage-plus = { workspace = true }
cw-utils        = { workspace = true }
schemars        = { workspace = true }
serde           = { workspace = true }
sg721           = { workspace = true }
thiserror       = { workspace = true }
