[config]
# Set this to `false` to run the tasks at workspace root directory and not on the members
default_to_workspace = false
# Set this to `true` to avoid clashes with core commands (e.g. `cargo make publish` vs `cargo publish`)
skip_core_tasks = true

[tasks.fmt]
command = "cargo"
args    = ["fmt", "--all", "--check"]

[tasks.test]
dependencies = [
  "lint",
  "unit-test",
  "int-test"
]

[tasks.unit-test]
command = "cargo"
args    = ["test", "--locked", "-p", "dega-cw721", "-p", "dega-minter"]

[tasks.int-test]
script = """
cd test-tool
npm run test
"""

[tasks.lint]
command = "cargo"
args    = ["clippy", "--tests", "--", "-D", "warnings"]

[tasks.build-raw]
command = "cargo"
args    = ["build", "--release", "--locked", "--target", "wasm32-unknown-unknown", "-p", "dega-cw721", "-p", "dega-minter"]

[tasks.build]
# https://hub.docker.com/r/cosmwasm/workspace-optimizer/tags https://hub.docker.com/r/cosmwasm/workspace-optimizer-arm64/tags
script = """
if [[ -d "artifacts" ]]; then
  rm artifacts/*
fi

if [[ $(arch) == "arm64" ]]; then
  image="cosmwasm/workspace-optimizer-arm64"
else
  image="cosmwasm/workspace-optimizer"
fi

docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  ${image}:0.15.0

if [[ -d "artifacts-optimized" ]]; then
  rm -rf artifacts-optimized/*
fi

mkdir -p artifacts-optimized

mv artifacts/* artifacts-optimized/
rmdir artifacts
"""

[tasks.schema]
script = """
#for d in packages/*; do
#  if [ -d "$d" ]; then
#    cd $d
#    cargo schema
#    cd ../..
#  fi
#done

for d in contracts/*; do
  if [ -d "$d" ]; then
    cd $d
    cargo schema
    cd ../..
  fi
done

rm -rf contracts/**/schema/raw
"""